version: "3.8"

services:
  api:
    image: zalinarusinova/iris_app:latest
    container_name: api
    restart: "on-failure"

  proxy:
    image: nginx
    container_name: proxy
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    restart: "on-failure"
    ports:
     - "80:80"
